name: shochateyo
description: ShochaTeyo - Drama Pendek Vertikal Premium
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  iconsax: ^0.0.8
flutter:
  uses-material-design: true
